/**
 * This class is generated by jOOQ
 */
package com.github.funnygopher.crowddj.jooq;


import com.github.funnygopher.crowddj.jooq.tables.Playlist;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in PUBLIC
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

	/**
	 * The table PUBLIC.PLAYLIST
	 */
	public static final Playlist PLAYLIST = com.github.funnygopher.crowddj.jooq.tables.Playlist.PLAYLIST;
}
