/**
 * This class is generated by jOOQ
 */
package com.github.funnygopher.crowddj.client.database.jooq;


import javax.annotation.Generated;

import org.jooq.Sequence;
import org.jooq.impl.SequenceImpl;


/**
 * Convenience access to all sequences in PUBLIC
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sequences {

	/**
	 * The sequence <code>PUBLIC.SYSTEM_SEQUENCE_1133B1A6_1D24_4F3F_830E_0C4C1D6A103A</code>
	 */
	public static final Sequence<Long> SYSTEM_SEQUENCE_1133B1A6_1D24_4F3F_830E_0C4C1D6A103A = new SequenceImpl<Long>("SYSTEM_SEQUENCE_1133B1A6_1D24_4F3F_830E_0C4C1D6A103A", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT);
}
