/**
 * This class is generated by jOOQ
 */
package com.github.funnygopher.crowddj.jooq.tables;


import com.github.funnygopher.crowddj.jooq.Keys;
import com.github.funnygopher.crowddj.jooq.Public;
import com.github.funnygopher.crowddj.jooq.tables.records.PlaylistRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Playlist extends TableImpl<PlaylistRecord> {

	private static final long serialVersionUID = 260183239;

	/**
	 * The reference instance of <code>PUBLIC.PLAYLIST</code>
	 */
	public static final Playlist PLAYLIST = new Playlist();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<PlaylistRecord> getRecordType() {
		return PlaylistRecord.class;
	}

	/**
	 * The column <code>PUBLIC.PLAYLIST.ID</code>.
	 */
	public final TableField<PlaylistRecord, Integer> ID = createField("ID", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>PUBLIC.PLAYLIST.FILEPATH</code>.
	 */
	public final TableField<PlaylistRecord, String> FILEPATH = createField("FILEPATH", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this, "");

	/**
	 * Create a <code>PUBLIC.PLAYLIST</code> table reference
	 */
	public Playlist() {
		this("PLAYLIST", null);
	}

	/**
	 * Create an aliased <code>PUBLIC.PLAYLIST</code> table reference
	 */
	public Playlist(String alias) {
		this(alias, PLAYLIST);
	}

	private Playlist(String alias, Table<PlaylistRecord> aliased) {
		this(alias, aliased, null);
	}

	private Playlist(String alias, Table<PlaylistRecord> aliased, Field<?>[] parameters) {
		super(alias, Public.PUBLIC, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Identity<PlaylistRecord, Integer> getIdentity() {
		return Keys.IDENTITY_PLAYLIST;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<PlaylistRecord> getPrimaryKey() {
		return Keys.CONSTRAINT_9;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<PlaylistRecord>> getKeys() {
		return Arrays.<UniqueKey<PlaylistRecord>>asList(Keys.CONSTRAINT_9);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Playlist as(String alias) {
		return new Playlist(alias, this);
	}

	/**
	 * Rename this table
	 */
	public Playlist rename(String name) {
		return new Playlist(name, null);
	}
}
